### PR TITLE
Add all payments to CLI

### LINKED ISSUE #167: Add All Payments Endpoint to CLI
### Expected Behavior
```
stellar payments all
```
This should also take cursor, order, and page-limit as arguments.

### Payment details to display
```
id
to
from
asset
amount
```
https://www.stellar.org/developers/horizon/reference/endpoints/payments-all.html

### PR DESCRIPTION
**Pull request by robertDurst**
So I'll admit there is some nice copy-pasta here -- this is very similar to the ledgers payments cli.

However, I did find an error in the current CLI payments (found in both the ledgers and transactions). If you scrolled through until you found a path_payment, you would see that you get the error:

> Missing fields for path_payment operation.

The reason for this is that `source_amount` does not exist for path payments. See here:

https://www.stellar.org/laboratory/#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjAwNzk0ZGUyYmQxYzEyMTliMzUyNjU3YmNlMWU0ZDhjZTJmNjA3MzdiYzU1OGZmM2MwNDZiMTRkZTRhYWExMGQifQ%3D%3D&network=public

This field only exists on payment paths, an object describing an intermediate step on a path_payment.

### Is there a GIF that reflects how this work made you feel?

Closes #167

### CODE REVIEW

**Comment by correlator** [comment]
It looks like this was built on an old version of master before we introduced the formatter and simple formatter.  When i was on the plane yesterday I actually tackled this one and didn't claim the issue.  You can use this branch as a guide to implement the formatter on payments https://github.com/kbacha/stellar-sdk/tree/scott/all_payments .   Nice catch on source_amount!  👍

**Comment by robertDurst** [comment]
@correlator sorry about that, didn't see that you had claimed that until after I submitted the PR.

I'll clean this up.

**Comment by robertDurst** [comment]
@correlator may be best to just merge your changes and then remove the source_amount. lmk what you think

**Comment by correlator** [comment]
@robertDurst you sure?  I'm happy to let you run with this.  If you close this PR I'll open mine up.  Whatever makes you happy :)

**Comment by robertDurst** [comment]
@correlator all good man, I'll just move on to the next!

**Comment by correlator** [comment]
right on.  BTW solid gif game here

**Pull request closed without merging**
